_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 1
                - 2
                - 13
                - 16
                - 23
                - 24
                - 55
                - 61
            "4": 3.11.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 4
epochs:
    value: 2
learning_rate:
    value: 0.01
test_size:
    value: 1000
train_size:
    value: 2000
weight_decay:
    value: 0
zero_init_residual:
    value: false
